version: '3.8'

services:
  server:
    build: ./
    ports:
      - 3000:3000
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: "mongodb://root:mongopass@database:27017/paymentdb?authSource=admin"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - database-data:/data/db

volumes:
  database-data:
