service: fiap-tech-challenge-payment
frameworkVersion: '3'

provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    ORDER_URL: ${env:ORDER_URL}
    AUTHORIZATION_URL: ${env:AUTHORIZATION_URL}
    PAYMENT_GATEWAY_CALLBACK_URL: ${env:PAYMENT_GATEWAY_CALLBACK_URL}
    AWS_SQS_PAYMENT_APPROVED_QUEUE_URL: ${env:AWS_SQS_PAYMENT_APPROVED_QUEUE_URL}
    AWS_SQS_PAYMENT_REJECTED_QUEUE_URL: ${env:AWS_SQS_PAYMENT_REJECTED_QUEUE_URL}
  tags:
    PROJECT: fiap-tech-challenge
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: ${env:AWS_SQS_PAYMENT_APPROVED_QUEUE_ARN}
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: ${env:AWS_SQS_PAYMENT_REJECTED_QUEUE_ARN}

functions:
  app:
    handler: dist/main/lambda.handler
    events:
      - httpApi:
          method: 'ANY'
          path: '/{proxy+}'
  onOrderAdded:
    handler: dist/main/lambda.onOrderAdded
    events:
      - sqs: ${env:AWS_SQS_ORDER_ADDED_QUEUE_ARN}

plugins:
  - serverless-offline
